import { createContext, useContext, useState, useEffect } from 'react';
import { useRouter } from 'next/router';
import { getToken, logout } from '../utils/auth';

//SELECT CONCAT('"', codename, '",') AS formatted_codenames FROM `auth_permission`; 

const UserPermissionsContext = createContext();

export const UserPermissionsProvider = ({ children }) => {
    const [permissions, setPermissions] = useState([]);
    const router = useRouter();

    useEffect(() => {
        const token = getToken(); // Get the token

        if (!token) {
            console.log('No token found, skipping permissions fetch.');
            return;
        }

        const fetchPermissions = async () => {
            try {
                const response = await fetch(`${process.env.NEXT_PUBLIC_API_BASE_URL}${process.env.NEXT_PUBLIC_API_ENDPOINT_USER_PERMISSIONS}`, {
                    headers: {
                        'Content-Type': 'application/json',
                        'Authorization': `Token ${token}`, 
                    },
                });

                if (!response.ok) {
                    throw new Error('Failed to fetch permissions');
                }

                const data = await response.json();
                console.log("Fetched permissions:", data); // Debugging log
                setPermissions(data);
            } catch (error) {
                console.error('Error fetching user permissions:', error);
                performClientSideLogout();
            }
        };

        fetchPermissions();
    }, []);

    function performClientSideLogout() {
        logout(); 
        router.push('/signin');
    }

    const canPerformAction = (action) => {
        if (!Array.isArray(permissions)) {
            return false; // Handle case where permissions is not an array
        }
        return permissions.some((permission) => permission.codename === action);
    };

    const permissionsKeys = [
        "add_logentry",
        "change_logentry",
        "delete_logentry",
        "view_logentry",
        "add_permission",
        "change_permission",
        "delete_permission",
        "view_permission",
        "add_group",
        "change_group",
        "delete_group",
        "view_group",
        "add_user",
        "change_user",
        "delete_user",
        "view_user",
        "add_historicaluser",
        "change_historicaluser",
        "delete_historicaluser",
        "view_historicaluser",
        "add_contenttype",
        "change_contenttype",
        "delete_contenttype",
        "view_contenttype",
        "add_session",
        "change_session",
        "delete_session",
        "view_session",
        "add_token",
        "change_token",
        "delete_token",
        "view_token",
        "add_tokenproxy",
        "change_tokenproxy",
        "delete_tokenproxy",
        "view_tokenproxy",
        "add_passwordresettoken",
        "change_passwordresettoken",
        "delete_passwordresettoken",
        "view_passwordresettoken",
        "add_userotp",
        "change_userotp",
        "delete_userotp",
        "view_userotp",
        "add_historicalpasswordresettoken",
        "change_historicalpasswordresettoken",
        "delete_historicalpasswordresettoken",
        "view_historicalpasswordresettoken",
        "add_historicaluserotp",
        "change_historicaluserotp",
        "delete_historicaluserotp",
        "view_historicaluserotp",
        "add_extendeduser",
        "change_extendeduser",
        "delete_extendeduser",
        "view_extendeduser",
        "add_historicalextendeduser",
        "change_historicalextendeduser",
        "delete_historicalextendeduser",
        "view_historicalextendeduser",
        "add_university",
        "change_university",
        "delete_university",
        "edit_view_university",
        "view_university",
        "add_researchinterestoptions",
        "change_researchinterestoptions",
        "delete_researchinterestoptions",
        "view_researchinterestoptions",
        "add_document",
        "change_document",
        "delete_document",
        "view_document",
        "add_historicaldocument",
        "change_historicaldocument",
        "delete_historicaldocument",
        "view_historicaldocument",
        "add_historicalresearchinterestoptions",
        "change_historicalresearchinterestoptions",
        "delete_historicalresearchinterestoptions",
        "view_historicalresearchinterestoptions",
        "add_historicaluserdocument",
        "change_historicaluserdocument",
        "delete_historicaluserdocument",
        "view_historicaluserdocument",
        "add_userdocument",
        "change_userdocument",
        "delete_userdocument",
        "view_userdocument",
        "add_historicaluserdetails",
        "change_historicaluserdetails",
        "delete_historicaluserdetails",
        "view_historicaluserdetails",
        "add_userdetails",
        "change_userdetails",
        "delete_userdetails",
        "view_userdetails",
        "add_researchinterest",
        "change_researchinterest",
        "delete_researchinterest",
        "view_researchinterest",
        "add_historicalvisa",
        "change_historicalvisa",
        "delete_historicalvisa",
        "view_historicalvisa",
        "add_historicalresearchinterest",
        "change_historicalresearchinterest",
        "delete_historicalresearchinterest",
        "view_historicalresearchinterest",
        "add_historicalcitizenship",
        "change_historicalcitizenship",
        "delete_historicalcitizenship",
        "view_historicalcitizenship",
        "add_citizenship",
        "change_citizenship",
        "delete_citizenship",
        "view_citizenship",
        "add_visa",
        "change_visa",
        "delete_visa",
        "view_visa",
        "add_customfield",
        "change_customfield",
        "delete_customfield",
        "view_customfield",
        "add_emailtemplate",
        "change_emailtemplate",
        "delete_emailtemplate",
        "view_emailtemplate",
        "add_escalationexclusion",
        "change_escalationexclusion",
        "delete_escalationexclusion",
        "view_escalationexclusion",
        "add_followup",
        "change_followup",
        "delete_followup",
        "view_followup",
        "add_ignoreemail",
        "change_ignoreemail",
        "delete_ignoreemail",
        "view_ignoreemail",
        "add_kbcategory",
        "change_kbcategory",
        "delete_kbcategory",
        "view_kbcategory",
        "add_kbitem",
        "change_kbitem",
        "delete_kbitem",
        "view_kbitem",
        "add_presetreply",
        "change_presetreply",
        "delete_presetreply",
        "view_presetreply",
        "add_queue",
        "change_queue",
        "delete_queue",
        "view_queue",
        "add_savedsearch",
        "change_savedsearch",
        "delete_savedsearch",
        "view_savedsearch",
        "add_ticket",
        "change_ticket",
        "delete_ticket",
        "view_ticket",
        "add_ticketcc",
        "change_ticketcc",
        "delete_ticketcc",
        "view_ticketcc",
        "add_ticketchange",
        "change_ticketchange",
        "delete_ticketchange",
        "view_ticketchange",
        "add_ticketcustomfieldvalue",
        "change_ticketcustomfieldvalue",
        "delete_ticketcustomfieldvalue",
        "view_ticketcustomfieldvalue",
        "add_ticketdependency",
        "change_ticketdependency",
        "delete_ticketdependency",
        "view_ticketdependency",
        "add_usersettings",
        "change_usersettings",
        "delete_usersettings",
        "view_usersettings",
        "add_kbiattachment",
        "change_kbiattachment",
        "delete_kbiattachment",
        "view_kbiattachment",
        "add_followupattachment",
        "change_followupattachment",
        "delete_followupattachment",
        "view_followupattachment",
        "add_checklist",
        "change_checklist",
        "delete_checklist",
        "view_checklist",
        "add_checklisttemplate",
        "change_checklisttemplate",
        "delete_checklisttemplate",
        "view_checklisttemplate",
        "add_checklisttask",
        "change_checklisttask",
        "delete_checklisttask",
        "view_checklisttask",
        "add_state",
        "change_state",
        "delete_state",
        "view_state",
        "add_language",
        "change_language",
        "delete_language",
        "view_language",
        "add_educationalbackground",
        "change_educationalbackground",
        "delete_educationalbackground",
        "view_educationalbackground",
        "add_historicaleducationalbackground",
        "change_historicaleducationalbackground",
        "delete_historicaleducationalbackground",
        "view_historicaleducationalbackground",
        "add_dissertation",
        "change_dissertation",
        "delete_dissertation",
        "view_dissertation",
        "add_historicaldissertation",
        "change_historicaldissertation",
        "delete_historicaldissertation",
        "view_historicaldissertation",
        "add_contactus",
        "change_contactus",
        "delete_contactus",
        "view_contactus",
        "add_historicalcontactus",
        "change_historicalcontactus",
        "delete_historicalcontactus",
        "view_historicalcontactus",
        "add_historicalresearchexperience",
        "change_historicalresearchexperience",
        "delete_historicalresearchexperience",
        "view_historicalresearchexperience",
        "add_researchexperience",
        "change_researchexperience",
        "delete_researchexperience",
        "view_researchexperience",
        "add_accessattempt",
        "change_accessattempt",
        "delete_accessattempt",
        "view_accessattempt",
        "add_countries",
        "change_countries",
        "delete_countries",
        "view_countries",
        "add_geoadmin1",
        "change_geoadmin1",
        "delete_geoadmin1",
        "view_geoadmin1",
        "add_geoadmin2",
        "change_geoadmin2",
        "delete_geoadmin2",
        "view_geoadmin2",
        "add_historicalcountries",
        "change_historicalcountries",
        "delete_historicalcountries",
        "view_historicalcountries",
        "add_historicalgeoadmin1",
        "change_historicalgeoadmin1",
        "delete_historicalgeoadmin1",
        "view_historicalgeoadmin1",
        "add_historicalgeoadmin2",
        "change_historicalgeoadmin2",
        "delete_historicalgeoadmin2",
        "view_historicalgeoadmin2",
        "add_educationalorganizationscategory",
        "change_educationalorganizationscategory",
        "delete_educationalorganizationscategory",
        "view_educationalorganizationscategory",
        "add_educationalorganizations",
        "change_educationalorganizations",
        "delete_educationalorganizations",
        "view_educationalorganizations",
        "add_historicaleducationalorganizations",
        "change_historicaleducationalorganizations",
        "delete_historicaleducationalorganizations",
        "view_historicaleducationalorganizations",
        "add_historicaleducationalorganizationscategory",
        "change_historicaleducationalorganizationscategory",
        "delete_historicaleducationalorganizationscategory",
        "view_historicaleducationalorganizationscategory",
        "add_skilloptions",
        "change_skilloptions",
        "delete_skilloptions",
        "view_skilloptions",
        "add_historicalskilloptions",
        "change_historicalskilloptions",
        "delete_historicalskilloptions",
        "view_historicalskilloptions",
        "add_awardgrantscholarship",
        "change_awardgrantscholarship",
        "delete_awardgrantscholarship",
        "view_awardgrantscholarship",
        "add_historicalskill",
        "change_historicalskill",
        "delete_historicalskill",
        "view_historicalskill",
        "add_trainingworkshop",
        "change_trainingworkshop",
        "delete_trainingworkshop",
        "view_trainingworkshop",
        "add_workexperience",
        "change_workexperience",
        "delete_workexperience",
        "view_workexperience",
        "add_historicalworkexperience",
        "change_historicalworkexperience",
        "delete_historicalworkexperience",
        "view_historicalworkexperience",
        "add_skill",
        "change_skill",
        "delete_skill",
        "view_skill",
        "add_historicalawardgrantscholarship",
        "change_historicalawardgrantscholarship",
        "delete_historicalawardgrantscholarship",
        "view_historicalawardgrantscholarship",
        "add_publication",
        "change_publication",
        "delete_publication",
        "view_publication",
        "add_historicalpublication",
        "change_historicalpublication",
        "delete_historicalpublication",
        "view_historicalpublication",
        "add_historicaltrainingworkshop",
        "change_historicaltrainingworkshop",
        "delete_historicaltrainingworkshop",
        "view_historicaltrainingworkshop",
        "add_campus",
        "change_campus",
        "delete_campus",
        "view_campus",
        "add_historicalcampus",
        "change_historicalcampus",
        "delete_historicalcampus",
        "view_historicalcampus",
        "add_historicalcollege",
        "change_historicalcollege",
        "delete_historicalcollege",
        "view_historicalcollege",
        "add_college",
        "change_college",
        "delete_college",
        "view_college",
        "add_department",
        "change_department",
        "delete_department",
        "view_department",
        "add_historicaldepartment",
        "change_historicaldepartment",
        "delete_historicaldepartment",
        "view_historicaldepartment",
        "add_facultymembers",
        "change_any_facultymember",
        "change_facultymembers",
        "change_own_facultymember",
        "delete_any_facultymember",
        "delete_facultymembers",
        "delete_own_facultymember",
        "view_any_facultymember",
        "view_facultymembers",
        "view_own_facultymember",
        "add_historicalfacultymembers",
        "change_historicalfacultymembers",
        "delete_historicalfacultymembers",
        "view_historicalfacultymembers",
        "add_historicalvolunteeractivity",
        "change_historicalvolunteeractivity",
        "delete_historicalvolunteeractivity",
        "view_historicalvolunteeractivity",
        "add_volunteeractivity",
        "change_volunteeractivity",
        "delete_volunteeractivity",
        "view_volunteeractivity",
        "add_historicalreferenceinfo",
        "change_historicalreferenceinfo",
        "delete_historicalreferenceinfo",
        "view_historicalreferenceinfo",
        "add_referenceinfo",
        "change_referenceinfo",
        "delete_referenceinfo",
        "view_referenceinfo",
        "add_historicaltestscore",
        "change_historicaltestscore",
        "delete_historicaltestscore",
        "view_historicaltestscore",
        "add_testscore",
        "change_testscore",
        "delete_testscore",
        "view_testscore",
        "add_group",
        "change_group",
        "delete_group",
        "view_group",
        "add_organizationcollegegroup",
        "change_organizationcollegegroup",
        "delete_organizationcollegegroup",
        "view_organizationcollegegroup",
        "add_customgroup",
        "change_customgroup",
        "delete_customgroup",
        "view_customgroup",
        "add_benefit",
        "change_benefit",
        "delete_benefit",
        "view_benefit",
        "add_historicalbenefit",
        "change_historicalbenefit",
        "delete_historicalbenefit",
        "view_historicalbenefit",
        "add_historicalfunding",
        "change_historicalfunding",
        "delete_historicalfunding",
        "view_historicalfunding",
        "add_college_funding",
        "add_department_funding",
        "add_edu_org_funding",
        "add_faculty_funding",
        "add_funding",
        "add_others_funding",
        "change_funding",
        "delete_funding",
        "view_funding",
        "add_programdraft",
        "change_programdraft",
        "delete_programdraft",
        "view_programdraft",
        "add_historicalprogram",
        "change_historicalprogram",
        "delete_historicalprogram",
        "view_historicalprogram",
        "add_historicalprogramdraft",
        "change_historicalprogramdraft",
        "delete_historicalprogramdraft",
        "view_historicalprogramdraft",
        "add_program",
        "change_program",
        "delete_program",
        "view_program",
        "add_dashboardwidget",
        "change_dashboardwidget",
        "delete_dashboardwidget",
        "view_active_user_widget",
        "view_campus_details_widget",
        "view_campus_overview_widget",
        "view_campus_widget",
        "view_dashboardwidget",
        "view_department_details_widget",
        "view_department_overview_widget",
        "view_department_widget",
        "view_funding_widget",
        "view_institution_widget",
        "view_logs_overview_widget",
        "view_mailing_overview_widget",
        "view_organization_details_widget",
        "view_organization_overview_widget",
        "view_server_health_widget",
        "view_user_chart_widget",
        "view_user_registration_overview_widget",
        // Add more keys as needed for other entities
    ];

    // Create a permissions object dynamically
    const permissionsObject = {};

    permissionsKeys.forEach(key => {
        const action = key.split('_')[0]; // Extracting the action part (e.g., 'add')
        permissionsObject[`can${action.charAt(0).toUpperCase() + action.slice(1)}`] = canPerformAction(key);
    });

    return (
        <UserPermissionsContext.Provider value={permissionsObject}>
            {children}
        </UserPermissionsContext.Provider>
    );
};

export const useUserPermissions = () => useContext(UserPermissionsContext);

